openapi: 3.0.3

info:
  title: WARAN - Impuls zur Erstellung einer Status API zur steuerbaren Ressource (SR)
  version: 0.5.2
  description: >
    API zur Abfrage aktueller und historischer Steuerungsvorgaben,
    Betriebszustände sowie Steuerbarkeitsnachweise für steuerbare
    Ressourcen.

    Über diese API kann der Status einer steuerbaren Ressource abgefragt werden.
    Ziel ist es, berechtigten Akteuren transparent darzustellen, ob und welche
    Handlungsoptionen hinsichtlich der Anlage bestehen.

    Folgende Dienste werden bereitgestellt:

    - Status-01 "residualLimits":
      Konsolidierte Steuerungsvorgaben der nächsten 48 Stunden.

    - Status-02 "limitsHistory":
      Historische Steuerungsvorgaben inklusive Status zur Ausführung

    - Status-03 "operatingStatus":
      Betriebs- und Kommunikationsstatus der steuerbaren Ressource und
      unterstützte lokale Use-Case

servers:
  - url: https://api.example.com/v1

tags:
  - name: Status Abfrage API
    description: Status- und Monitoring-Schnittstellen zur steuerbaren Ressource

paths:

  /from/MSB/status/residualLimits/v0:
    get:
      tags:
        - Status Abfrage API

      summary: Status-01 - Aktuelle resultierdne Steuerungshandlungen abrufen (Residualprofile)
      operationId: getActiveLimits

      description: >
        Liefert alle aktuellen sowie zukünftigen Steuerungsvorgaben als konsolidiertes Profil (Residualprofil) für die nächsten 48 Stunden.

        Enthalten sind:

        - Residualprofil Ad-Hoc-Steuerungen (LPC/LPP)


        - Residualprofil Flexbandvorgaben (POEN)


        Die zurückgegebenen Werte entsprechen den aktuell gültigen
        Leistungsgrenzen der steuerbaren Ressource. Es handelt sich um die vom MSB verarbeiteten und konsolidierten Steuerungshandlungen, wie sie auch an die lokale Steuerungseinheit weitergegeben werden. 
      parameters:
        - $ref: '#/components/parameters/TransactionId'
        - $ref: '#/components/parameters/CreationDateTime'
        - $ref: '#/components/parameters/LocationId'

      responses:
        '202':
          description: accepted - Konsolidierte Steuerungsvhandlungen der nächsten 48 Stunden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActiveControlLimitsResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '405':
          description: Method not allowed
        '415':
          description: Unsupported Media Type
        '422': 
          description: Unprocessable Entity
        '429':
          description: Too Many Requests
        '500':
          description: Internal Server Error
        '503':
          description: Service Unavailable
        '504':
          description: Gateway Timeout
  /from/MSB/status/historicalLimits/v0:
    get:
      tags:
        - Status Abfrage API

      summary: Status-02 - Historische Steuerungshandlungen abrufen
      operationId: getLimitsHistory

      description: >
        Liefert alle bekannten Steuerungsvorgaben innerhalb eines frei
        definierbaren Zeitraumes.

      parameters:
        - $ref: '#/components/parameters/TransactionId'
        - $ref: '#/components/parameters/CreationDateTime'

        - $ref: '#/components/parameters/LocationId'

        - name: from
          in: query
          required: false
          description: Startzeitpunkt der Historienabfrage
          schema:
            type: string
            format: date-time

        - name: until
          in: query
          required: false
          description: Endzeitpunkt der Historienabfrage
          schema:
            type: string
            format: date-time

      responses:
        '202':
          description: accepted - Historische Steuerungsvorgaben
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HistoricControlLimitsResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '405':
          description: Method not allowed
        '415':
          description: Unsupported Media Type
        '422': 
          description: Unprocessable Entity
        '429':
          description: Too Many Requests
        '500':
          description: Internal Server Error
        '503':
          description: Service Unavailable
        '504':
          description: Gateway Timeout

  /from/MSB/status/operatingState/v0:
    get:
      tags:
        - Status Abfrage API

      summary: Status-03 - Betriebsstatus steuerbarer Ressourcen abrufen
      operationId: getResourceStatus

      description: >
        Liefert aktuelle Informationen über den Betriebszustand,
        die Kommunikationsfähigkeit, unterstützte lokale Use-Cases
        sowie die dem Marktakteur zugewiesenen API-Berechtigungen.

      parameters:
        - $ref: '#/components/parameters/TransactionId'
        - $ref: '#/components/parameters/CreationDateTime'
        - $ref: '#/components/parameters/LocationId'

      responses:
        '202':
          description: accepted - Aktueller Betriebsstatus
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceStatusResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '405':
          description: Method not allowed
        '415':
          description: Unsupported Media Type
        '422': 
          description: Unprocessable Entity
        '429':
          description: Too Many Requests
        '500':
          description: Internal Server Error
        '503':
          description: Service Unavailable
        '504':
          description: Gateway Timeout

components:

  parameters:

    TransactionId:
      name: transactionId
      in: query
      required: true
      description: Eindeutige Transaktions-ID der Anfrage.
      schema:
        type: string
        maxLength: 64
        example: 754ce569-3d95-4d7b-87cc-1d8f22289a00

    CreationDateTime:
      name: creationDateTime
      in: query
      required: true
      description: Zeitpunkt der Erstellung der Anfrage.
      schema:
        type: string
        format: date-time
        example: "2026-07-09T06:56:21Z"



    LocationId:
      name: locationId
      in: query
      required: true
      example: 
        - C1234567897
        - C1234848431
      description: Eine oder mehrere Lokationskennungen (SR-ID's).
      style: form
      explode: true
      schema:
        type: array
        items:
          type: string

  schemas:

    PowerLimit:
      type: object

      required:
        - activePowerValue
        - executionTimeFrom
        - executionTimeUntil

      properties:

        activePowerValue:
          type: number
          example: 4.2
          format: double
          description: Wirkleistungswert in kW

        executionTimeFrom:
          type: string
          format: date-time

        executionTimeUntil:
          type: string
          format: date-time

    HistoricPowerLimit:
      allOf:
        - $ref: '#/components/schemas/PowerLimit'
        - type: object
          properties:

            executionStatus:
              type: string
              enum:
                - confirmed
                - accepted
                - rejected
                - unknown


    ActiveControlLimits:
      type: object

      properties:

        locationId:
          type: string
          example: C1234567897

        adHocResidualMaxConsumption:
          type: array
          items:
            $ref: '#/components/schemas/PowerLimit'

        adHocResidualMaxFeedIn:
          type: array
          items:
            $ref: '#/components/schemas/PowerLimit'


        poenResidualMinConsumption:
          type: array
          items:
            $ref: '#/components/schemas/PowerLimit'

        poenResidualMaxConsumption:
          type: array
          items:
            $ref: '#/components/schemas/PowerLimit'

        poenResidualMinFeedIn:
          type: array
          items:
            $ref: '#/components/schemas/PowerLimit'

        poenResidualMaxFeedIn:
          type: array
          items:
            $ref: '#/components/schemas/PowerLimit'

    HistoricControlLimits:
      type: object

      properties:

        locationId:
          type: string
          example: C1234567897


        periodStart:
          type: string
          format: date-time

        periodEnd:
          type: string
          format: date-time

        adHocValuesMaxConsumption:
          type: array
          items:
            $ref: '#/components/schemas/HistoricPowerLimit'

        adHocValuesMaxFeedIn:
          type: array
          items:
            $ref: '#/components/schemas/HistoricPowerLimit'

        poenValuesMinConsumption:
          type: array
          items:
            $ref: '#/components/schemas/HistoricPowerLimit'

        poenValuesMaxConsumption:
          type: array
          items:
            $ref: '#/components/schemas/HistoricPowerLimit'

        poenValuesMinFeedIn:
          type: array
          items:
            $ref: '#/components/schemas/HistoricPowerLimit'

        poenValuesMaxFeedIn:
          type: array
          items:
            $ref: '#/components/schemas/HistoricPowerLimit'
        softstartConsumption:
          type: array
          items:
            $ref: '#/components/schemas/HistoricPowerLimit'
        softstartProducction:
              type: array
              items:
                $ref: '#/components/schemas/HistoricPowerLimit'

    ActiveControlLimitsResponse:
      type: object

      required:
        - transactionId
        - creationDateTime
        - limits

      properties:
        transactionId:
          type: string
          maxLength: 64
          example: 754ce569-3d95-4d7b-87cc-1d8f22289a00 
          description: transactionId wird aus dem GET-Request übernommen und zurückgegeben

        creationDateTime:
          type: string
          format: date-time
          description: transactionId wird aus dem GET-Request übernommen und zurückgegeben


      #    type: string

        residualLimits:
          type: array
          items:
            $ref: '#/components/schemas/ActiveControlLimits'

    HistoricControlLimitsResponse:
      type: object

      required:
        - transactionId
        - creationDateTime
        - limits

      properties:

        transactionId:
          type: string
          maxLength: 64
          example: 754ce569-3d95-4d7b-87cc-1d8f22289a00 
          description: transactionId wird aus dem GET-Request übernommen und zurückgegeben

        creationDateTime:
          type: string
          format: date-time
          description: transactionId wird aus dem GET-Request übernommen und zurückgegeben

        historicalLimits:
          type: array
          items:
            $ref: '#/components/schemas/HistoricControlLimits'

    ResourceOperatingStatus:
      type: object
      required:
        - operatingState
        - lastConnectionTimestamp
      properties:

        operatingState:
          type: string
          example: active
          description: Aktueller Betriebszustand der Ressource.
          enum:
            - active
            - disturbance
            - transientCommunicationFailure 
            - localConnectionError
          decription: "active = Normaler Betriebsmodus; disturbance=Allgemeine Störung; transientCommunicationFailure = temporäre Kommunikationsstörug (bspw. < 24 Stunden); localConnectionError = Verbindung zur lokalen Gegenstelle verloren (bspw. Missing Heartbeats seit mehr als 2 Stunden)"

        description:
          type: string
          example: "Normalbetrieb, keine Störungen bekannt"

        connectedLocalDevice:
          description: "Verbundenes EEBUS Gerät (bspw. HEMS)"
          type: string
          example: i:983327_u:C8277H008F-3

        lastManagementConnectionTimestamp:
          description: "Letzte Kommunikation mit der MSB Steuereinheit"
          type: string
          format: date-time

        failureTimestamp:
          type: string
          format: date-time
          description: "Zeitpunkt seit dem eine Störung bekannt ist - also seitdem der 'operatingState' nicht mehr 'active' ist"

    SupportedLocalUseCases:
      type: object

      properties:

        relayConsumption:
          type: boolean
          example: false
          description: Lokale Verbrauchssteuerung über Relais.

        relayFeedIn:
          type: boolean
          example: false
          description: Lokale Einspeisesteuerung über Relais.

        EEBUS_LPC:
          type: boolean

        EEBUS_LPP:
          type: boolean

        EEBUS_POEN:
          type: boolean

        EEBUS_PODF:
          type: boolean

        EEBUS_TOUT:
          type: boolean

        EEBUS_MPC:
          type: boolean

    ApiPermission:
      type: object

      properties:

        apiName:
          type: string
          enum:
            - AdHoc-API
            - Flexband-API
            - EEBUS-Data-API
            - TAF-Config-API
            - Proxy-Data-API

        operatorAgreement:
          type: string
          description: Grundlage der Berechtigung.
          enum:
            - legal
            - contract

        activeFrom:
          type: string
          format: date-time

        activeTo:
          type: string
          format: date-time

    ResourceStatus:
      type: object

      required:
        - locationId
        - state

      properties:

        locationId:
          type: string
          example: C1234567897

        state:
          $ref: '#/components/schemas/ResourceOperatingStatus'

        supportedLocalUseCases:
          $ref: '#/components/schemas/SupportedLocalUseCases'



    ResourceStatusResponse:
      type: object

      required:
        - transactionId
        - creationDateTime
        - resources

      properties:

        transactionId:
          type: string
          maxLength: 64
          example: 754ce569-3d95-4d7b-87cc-1d8f22289a00 
          description: transactionId wird aus dem GET-Request übernommen und zurückgegeben

        creationDateTime:
          type: string
          format: date-time
          description: transactionId wird aus dem GET-Request übernommen und zurückgegeben

        resources:
          type: array
          items:
            $ref: '#/components/schemas/ResourceStatus'
